title: Komal Sinha
logo: /assets/img/logo.png
title: <p align="center"> Komal Sinha </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/komal-sinha-1bb3105b/">LinkedIn</a> |
  <a href="https://github.com/komal1721">GitHub</a>
  
  <br>   
  I'm working on Data Science, Machine learning, NLP & Deep Learning.
  <br>
  </p>
